/* eslint-disable @typescript-eslint/no-shadow */
/* eslint-disable no-nested-ternary */
/* eslint-disable radix */
import React, { useEffect } from 'react';
import {
  Autocomplete,
  Box,
  TextField,
  Button,
  InputAdornment,
  CircularProgress,
  Typography,
} from '@mui/material';
import { useAppDispatch, useAppSelector } from 'store/hooks';
import { InitialCreateRaw, ProductRaw } from 'models/b2b/ProductRaw';
import { useFormik } from 'formik';
import * as yup from 'yup';
import FormLabel from 'components/FormLabel';
import InputImage from 'components/InputImage';
import { Category } from 'models/b2b/Category';
import { NumberFormatValues, NumericFormat } from 'react-number-format';
import { rawAction } from 'store/slice/b2b/ProductRaw';
import { uiAction } from 'store/slice/ui';

interface RawProps {
  onClose: () => void;
  data: ProductRaw | null;
}

export default function RawForm({ onClose, data }: RawProps) {
  const dispatch = useAppDispatch();
  const raw = useAppSelector((state) => state.raw);
  const categories = useAppSelector((state) => state.raw.categories);

  const editValue: InitialCreateRaw = {
    file: data ? data.product_parent.image_filepath : '',
    name: data ? data.product_parent.name : '',
    category:
      data && data.product_parent.product_parent_category
        ? data.product_parent.product_parent_category
        : [],
    stock: data ? data.stock.toString() : '',
    description: data ? data.description : '',
  };

  // formik
  const initialValues: InitialCreateRaw = {
    file: '',
    name: '',
    category: [],
    stock: '',
    description: '',
  };
  const formik = useFormik({
    initialValues: data ? editValue : initialValues,
    onSubmit: async (values) => {
      if (data) {
        dispatch(
          rawAction.updateRaw({
            id: data.id,
            body: {
              description: values.description,
              stock: Number(parseFloat(values.stock.split('.').join(''))),
              name: values.name,
              category_ids:
                values.category.length > 0
                  ? values.category.map(({ id }) => id)
                  : [],
              image: values.file,
              is_active: data.is_active,
              is_exist: data.is_exist,
              parent_id: data.product_parent_id,
            },
          }),
        );
      } else {
        dispatch(
          rawAction.createRaw({
            description: values.description,
            stock: Number(parseFloat(values.stock.split('.').join(''))),
            name: values.name,
            category_ids:
              values.category.length > 0
                ? values.category.map(({ id }) => id)
                : [],
            image: values.file,
          }),
        );
      }
    },
    validationSchema: yup.object({
      file: yup.mixed().required('Please upload an image'),
      name: yup.string().required('Product Name is required'),
      category: yup.mixed().required('Category is required'),
      stock: yup.mixed().required('In Stock is required'),
    }),
  });

  const {
    handleSubmit,
    values,
    handleBlur,
    handleChange,
    errors,
    touched,
    setFieldValue,
    isValid,
    resetForm,
  } = formik;

  useEffect(() => {
    if (!raw.loadingForm && raw.isSuccessCreate) {
      onClose();
      resetForm();
      dispatch(
        uiAction.openYellowToast({
          totalItem: 1,
          additionalMsg: 'successfully',
          action: data ? 'successfully edited!' : 'added!',
          error: false,
          noUndo: true,
        }),
      );
      dispatch(rawAction.resetFormParam());
    }
  }, [raw.loadingForm, raw.isSuccessCreate]);

  return (
    <Box m={0}>
      <form onSubmit={handleSubmit}>
        <Box p="24px">
          {/* INPUT IMAGE */}
          <FormLabel
            text="Input Image"
            required
            error={Boolean(errors.file)}
            helperText={errors.file && `${errors.file}`}
          >
            <InputImage
              label="Image"
              width={720}
              height={720}
              value={values.file}
              onChange={(e: any) => setFieldValue('file', e)}
            />
          </FormLabel>
          {/* RAW ID (SHOWED WHEN EDIT) */}
          <Box display={data ? 'flex' : 'none'}>
            <FormLabel
              text="RAW ID"
              required
              helperText="RAW ID will be automatically generated by system"
            >
              <Box
                width="inherit"
                height="44px"
                borderRadius="8px"
                border="solid 1px #d5d5d5"
                bgcolor="#f5f7fa"
                display="flex"
                flexDirection="row"
                justifyContent="flex-start"
                alignItems="center"
                p="0"
              >
                <Box
                  bgcolor="#e4e4e4"
                  color="#232933"
                  fontWeight="bold"
                  height="42px"
                  display="flex"
                  flexDirection="row"
                  justifyContent="flex-start"
                  alignItems="center"
                  paddingX="8px"
                  mr="8px"
                  borderRadius="6.5px 0px 0px 6.5px"
                >
                  RAW
                </Box>
                <Typography color="#303030">{data?.id}</Typography>
              </Box>
            </FormLabel>
          </Box>
          {/* PRODUCT NAME */}
          <FormLabel
            text="Product Name (SKU)"
            required
            error={touched.name && Boolean(errors.name)}
            helperText={touched.name && errors.name && `${errors.name}`}
          >
            <TextField
              type="text"
              name="name"
              placeholder="Insert Name"
              value={values.name}
              onChange={handleChange}
              onBlur={handleBlur}
              fullWidth
              inputProps={{
                maxLength: 100,
              }}
            />
          </FormLabel>
          {/* CATEGORY */}
          <FormLabel
            text="Category"
            required
            error={touched.category && Boolean(errors.category)}
            helperText={
              touched.category && errors.category && `${errors.category}`
            }
          >
            <Autocomplete
              options={categories}
              multiple
              onChange={(e, value) => {
                setFieldValue('category', value);
              }}
              isOptionEqualToValue={(option, values) => {
                return option.id === values.id;
              }}
              getOptionLabel={(option: Category) => `${option.name}`}
              value={values.category}
              renderInput={(params) => (
                <TextField
                  {...params}
                  name="category"
                  onBlur={handleBlur}
                  placeholder="Choose Category"
                />
              )}
            />
          </FormLabel>
          {/* stock */}
          <FormLabel
            text="In Stock (gram)"
            required
            error={
              touched.stock &&
              (Boolean(errors.stock) || parseInt(values.stock) <= 0)
            }
            helperText={
              touched.stock &&
              ((errors.stock && `${errors.stock}`) ||
                (parseInt(values.stock) <= 0 && `Please input valid stock`))
            }
          >
            <NumericFormat
              name="stock"
              customInput={TextField}
              placeholder="Insert In Stock"
              onChange={(e) => setFieldValue('stock', e.target.value)}
              onBlur={handleBlur}
              value={values.stock}
              thousandSeparator="."
              decimalSeparator=","
              decimalScale={0}
              minLength={2}
              fullWidth
              allowNegative={false}
              isAllowed={(val: NumberFormatValues) => {
                const { floatValue } = val;
                return (
                  floatValue !== undefined &&
                  floatValue >= 1 &&
                  floatValue <= 9999999999
                );
              }}
              // eslint-disable-next-line react/jsx-no-duplicate-props
              InputProps={{
                endAdornment: (
                  <InputAdornment position="end">gram</InputAdornment>
                ),
              }}
            />
          </FormLabel>
          {/* description */}
          <FormLabel text="Description">
            <TextField
              id="description"
              value={values.description}
              fullWidth
              rows={4}
              multiline
              onChange={handleChange}
              onBlur={handleBlur}
              placeholder="Insert description"
              inputProps={{ maxLength: 100 }}
            />
          </FormLabel>
        </Box>
        <Box
          width="100%"
          display="flex"
          gap="10px"
          justifyContent="end"
          sx={{
            padding: '24px',
            boxShadow: '3px 0px 10px rgba(0, 0, 0, 0.1)',
          }}
        >
          <Button
            sx={{ width: 'max-content' }}
            type="submit"
            disabled={!isValid || raw.loadingForm}
          >
            {raw.loadingForm ? (
              <CircularProgress />
            ) : data ? (
              'Save Changes'
            ) : (
              'Create'
            )}
          </Button>
        </Box>
      </form>
    </Box>
  );
}
